### PR TITLE
ASD-13105 - Added status retry timeout to prevent infinite loop

### PR DESCRIPTION
**Pull request by michal-hynek**
@joshcbarnes please review, FYI @msquance 

GoodData API wrapper keeps polling the upload status endpoint until the upload has terminated.  It's possible for upload to get stuck if the wrapper keeps getting "PENDING" response.  I've added timeout logic for the status check to throw an exception after 1 hour.

### CODE REVIEW

**Comment by msquance** [comment]
Do we need to upgrade to 1.4.2 with this change? I'm less comfortable doing that in a patch.

**Comment by michal-hynek** [comment]
I think it's cleaner to update the version since we've updated the code.  I guess we don't have to update the version and just do `mvn deploy` and rebuild allocadia so it picks up the updated code.

@joshcbarnes thoughts?

**Comment by joshcbarnes** [comment]
We updated our version of the code, though, right?  I would think that updates to things inherited from GD and updates to code we maintain would be separately managed...i.e. just bump the version for our overall version of the library

**Comment by joshcbarnes** [comment]
Ok, I misunderstood

@msquance - he's bumping the version number himself to reflect updating our version of this library - 1.4.2 doesn't represent a different dependency pulled in from GD

Good to merge?

**Comment by msquance** [comment]
Ok, as long as we aren't pulling in an update from GoodData then I'm ok. It's a bit confusing though because 1.4.1 is a version from GD so what would we do when GoodData goes to version 1.4.2? Can we use 1.4.1.1 instead or the system doesn't go beyond x.y.z?

**Comment by joshcbarnes** [comment]
We could do that, though I don't think it's super important to keep our version and the GD version in sync.  We should still be denoting the GD version as a dependency within the project.  If anything I think keeping those numbers in sync might be more confusing

**Comment by michal-hynek** [comment]
I don't care either way about the version number.  Should I leave it as it is?

**Comment by joshcbarnes** [comment]
My vote would be to keep as is in this PR - @msquance is that ok?

**Comment by msquance** [comment]
Ok. Merge away.

**Pull request merged**
